language: cpp
compiler: clang

os: osx

branches:
  only:
  - master

jobs:
  include:
  - script:
    - cmake -DMBPBUILD:BOOL=OFF CMakeLists.txt
    - cmake --build . --target Rewind FrameRateUnlock

    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH
      file_glob: true
      file: ./*
      skip_cleanup: true

  - script:
    - cmake -DMBPBUILD:BOOL=ON CMakeLists.txt
    - cmake --build . --target Rewind FrameRateUnlock DiscordRPC

    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH
      file_glob: true
      file: ./*
      skip_cleanup: true