language: cpp
compiler: clang

os: osx

branches:
  only:
  - master

script:
  - cmake -DMBPBUILD:BOOL=ON CMakeLists.txt
  - cmake  --build . --target Rewind FrameRateUnlock DiscordRPC

deploy:
  provider: releases
  api_key: "73e9334c2604d90ced54e34dcd63a02dafed2767"
  file_glob: true
  file: ./*
  skip_cleanup: true