language: cpp
compiler: clang

os: osx

branches:
  only:
  - master

script:
  - cmake -DMBPBUILD:BOOL=OFF CMakeLists.txt
  - cmake  --build . --target Rewind FrameRateUnlock DiscordRPC

deploy:
  provider: releases
  api_key: "9931245ea403910e49d427b95fc3abde22968ea7"
  file_glob: true
  file: ./*
  skip_cleanup: true